### PR TITLE
Upgrade to index-provider v0.13.4

### PR DESCRIPTION
**Pull request by masih**
Upgrade to the latest index-provider library.

### CODE REVIEW

**Review by LexLuthr — APPROVED** [review]
LGTM!

**Review by dirkmc — APPROVED** [review]
LGTM 👍

**Comment by dirkmc** [comment]
@LexLuthr would you mind doing a sanity check on a local devnet to make sure ipni still behaves as expected with this change.
Could you please also note the steps that you take to test it, so that we can build an itest to perform the test automatically for future updates.

**Comment by LexLuthr** [comment]
Head before a deal on new devnet:

```
ipni ads get --addr-info /ip4/127.0.0.1/tcp/50000/p2p/12D3KooWCF8kX19u7Jtqpcjc2hKZ9Zmnd8QdqQps6aWt7QySS3bZ --topic "/indexer/ingest/localnet-9e22673c-981c-47a1-a6e4-a180f5a38941" --head
CID:          baguqeerawr2jefcpptrlolg45oyyg4xxh24vlw6zxnrlls5hoa5nenx32pxa
PreviousCID:  baguqeeracu4g3alpgvrkfuvp273gkljmvsfscetgh2joh3wcpdwnu42nbflq
ProviderID:   12D3KooWCF8kX19u7Jtqpcjc2hKZ9Zmnd8QdqQps6aWt7QySS3bZ
ContextID:    
Addresses:    [/ip4/127.0.0.1/tcp/50000 /ip4/172.18.0.3/tcp/50000]
Is Remove:    false
Metadata :    
Extended Providers:
   Override: false
   Providers:
      None
Signature: ✅ valid
Signed by: content provider
Entries:
  Chunk Count: 0
  Total Count: 0
```

Head after a sample deal was made:

```
ipni ads get --addr-info /ip4/127.0.0.1/tcp/50000/p2p/12D3KooWCF8kX19u7Jtqpcjc2hKZ9Zmnd8QdqQps6aWt7QySS3bZ --topic "/indexer/ingest/localnet-9e22673c-981c-47a1-a6e4-a180f5a38941" --head -e
CID:          baguqeerauw2iabvuecv3xihwcmfi7e7fha7lgpbm7rqh4pkdu2smlbkwtv7a
PreviousCID:  baguqeerawr2jefcpptrlolg45oyyg4xxh24vlw6zxnrlls5hoa5nenx32pxa
ProviderID:   12D3KooWCF8kX19u7Jtqpcjc2hKZ9Zmnd8QdqQps6aWt7QySS3bZ
ContextID:    AXESIGIFk5E93Rx8z40kRpi6YHgSLByX2Zitk+gRPNQ9P1Av
Addresses:    [/ip4/127.0.0.1/tcp/50000 /ip4/172.18.0.3/tcp/50000]
Is Remove:    false
Metadata :    kBKjaFBpZWNlQ0lE2CpYKAABgeIDkiAg8rmli7ydmFblLquFFVwbopj36N9Fi9IKOtdn4RVyyiJsVmVyaWZpZWREZWFs9G1GYXN0UmV0cmlldmFs9Q==
Extended Providers:
   None
Signature: ✅ valid
Signed by: content provider
Entries:
  2DrjgbGYgWUZgcasYgbyiBrRRKHz1maZwDbN9C6pBb3eFSbDjL
  ---------------------
  Chunk Count: 1
  Total Count: 1
```

The steps are simple:
1. Start a new devnet
2. Find the network name
3. Not the current head
4. Make a deal and wait for it to publish
5. Get the head again and verify that it changed
6. Ensure new head has 1 entry (as sample deal uses just 1 file)

**Comment by LexLuthr** [comment]
@dirkmc If you want I can write up a simple itest which does the following.

1. Start a new devnet
2. Get the current head
3. Make a deal and wait for it to publish
4. Get the head again and verify that it changed. Match the previous CID of new head to previous head. Must match
5. Ensure new head has
    a. Type is not removed 
    b. Had at least 1 entry

**Pull request merged**
