### PR TITLE
chore: update to lotus release/v1.21.0

### PR DESCRIPTION
**Pull request by jacobheun**
Based on top of https://github.com/filecoin-project/boost/pull/1293, but updates to the latest commit, https://github.com/filecoin-project/lotus/commit/33e41ce8a96097730bfcde7a22325dba41efbc2a,  for the pending release branch for Lotus 1.21.0

TODO:
- [ ] Update ffi submodule to match lotus

### CODE REVIEW

**Comment by rjan90** [comment]
Hey @jacobheun! Just wanted to let you know that the current lotus `release/1.21.0` branch is expected to be [reset to the current master](https://filecoinproject.slack.com/archives/CP50PPW2X/p1678902416402809), which includes all the rpc enhancements from the last couple days, and also includes the new version updates of [go-data-transfer v2 and libp2p](https://filecoinproject.slack.com/archives/CP50PPW2X/p1678902416402809).

Can send a nudge here when the new release/v1.21.0 branch is out.

**Comment by rjan90** [comment]
Hey @jacobheun! The [release/v1.21.0](https://github.com/filecoin-project/lotus/tree/release/v1.21.0) branch has now been reset to the current master and is expected to be shipped today

**Comment by jacobheun** [comment]
Thanks @rjan90! I'll get this updated with the latest and we'll aim to get a 1.7.0-rc for boost out following the lotus release.

**Comment by jacobheun** [comment]
The latest version of the lotus release/1.21.0 branch includes updates an update to go-data-transfer v2. This is going to require a bit more work and testing on our end to have a compatible branch out as we need to update quite a few apis.

**Comment by jacobheun** [comment]
The Boost 1.6.2-rc2 release now supports v1.21.x lotus and is also compatible with Lotus 1.20.x, the compatibility matrix is up to date - https://boost.filecoin.io/getting-started#boost-and-lotus-compatibility-matrix. This PR was superseded by https://github.com/filecoin-project/boost/pull/1333

**Pull request closed without merging**
