### PR TITLE
chore(deps): upgrade graphsync for identity CID fix

### PR DESCRIPTION
**Pull request by rvagg**

### CODE REVIEW

**Comment by rvagg** [comment]
test failing because the test itself uses an identity CID for "missing" .. working on some additional tests and possible changes to handle identity CIDs through a retrieval cycle

**Comment by rvagg** [comment]
OK, this is a bit of a problem and I'm going to have to take an alternative approach with graphsync because of classic online deal flow and it's reliance on identity CIDs being non-simulated blocks _everywhere_.

**Review by LexLuthr — COMMENTED** [review]
The new itest is still not in circleCI.

**Review by LexLuthr — APPROVED** [review]

**Review by LexLuthr — APPROVED** [review]
LGTM!

**Pull request merged**
