### PR TITLE
fix: close piece reader after generating indexes

### PR DESCRIPTION
**Pull request by LexLuthr**
Fixes https://github.com/filecoin-project/lotus/issues/10935

- [x] Test on SP

### CODE REVIEW

**Review by nonsense — APPROVED** [review]

**Comment by bobdubois** [comment]
this fix solved the issue of locked deleted files from the unsealed folder.

**Comment by Shekelme** [comment]
I'm very sorry, but right after applying this commit, I started to observe such errors (on two different miners):
```13.     2023-09-23 21:35:43 +0300 MSK:  [event;sealing.SectorMarkForUpdate]     {"User":{}}
14.     2023-09-23 21:35:43 +0300 MSK:  [event;sealing.SectorStartCCUpdate]     {"User":{}}
15.     2023-09-23 21:35:43 +0300 MSK:  [event;sealing.SectorAddPiece]  {"User":{}}
16.     2023-09-23 21:35:43 +0300 MSK:  [event;sealing.SectorAddPiece]  {"User":{}}
17.     2023-09-23 21:35:43 +0300 MSK:  [event;sealing.SectorAddPieceFailed]    {"User":{}}
        writing piece: storage call error 0: pr read error: unexpected EOF [name: lenovo21]: pr read error: unexpected EOF
18.     2023-09-23 21:35:43 +0300 MSK:  [event;sealing.SectorRetryWaitDeals]    {"User":{}}
19.     2023-09-23 21:35:43 +0300 MSK:  [event;sealing.SectorStartPacking]      {"User":{}}
20.     2023-09-23 21:35:43 +0300 MSK:  [event;sealing.SectorAbortUpgrade]      {"User":{}}
        sector had no deals
21.     2023-09-23 21:35:43 +0300 MSK:  [event;sealing.SectorRevertUpgradeToProving]    {"User":{}}```
Rolling back to vanilla boost v2.0.0 helps.
My versions:
```admfc@lenovo92:~$ go version
go version go1.20.7 linux/amd64
admfc@lenovo92:~$ rusrup -v
Command 'rusrup' not found, did you mean:
  command 'rustup' from snap rustup (1.24.3)
See 'snap info <snapname>' for additional versions.
admfc@lenovo92:~$ rustc --version
rustc 1.71.1 (eb26296b5 2023-08-03)
admfc@lenovo92:~$ npm --version
8.19.4
admfc@lenovo92:~$ lotus --version
lotus version 1.23.3+mainnet+git.7bb1f98ac
admfc@lenovo92:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy
admfc@lenovo92:~$ uname -a
Linux lenovo92 5.15.0-79-generic #86-Ubuntu SMP Mon Jul 10 16:07:21 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by strahe** [comment]
Should we release a fixed version? Currently the latest v2.0.0 and 2.1.0-rc do not contain this fix.

**Comment by LexLuthr** [comment]
@strahe Hey! We will cutting a new RC with the fix either today to tomorrow.

**Pull request merged**
