### PR TITLE
deps: Update go-libp2p to v0.27.1

### PR DESCRIPTION
**Pull request by MarcoPolo**
I simply ran `go get github.com/libp2p/go-libp2p` to update to the latest v0.27.1. Lots of updates here (https://github.com/libp2p/go-libp2p/releases) including fixing a nasty busy loop bug in the autorelay module (see https://github.com/libp2p/go-libp2p/pull/2208).

### CODE REVIEW

**Comment by jacobheun** [comment]
This is blocked on the lotus PR https://github.com/filecoin-project/lotus/pull/10671 landing atm

**Comment by BigLep** [comment]
https://github.com/filecoin-project/lotus/pull/10671 is merged.  What are the next steps here?

**Comment by MarcoPolo** [comment]
Updated to v0.27.3 to match https://github.com/filecoin-project/lotus/pull/10671

**Comment by MarcoPolo** [comment]
No longer needed \o/

**Pull request closed without merging**
